name: Build, Push Docker & Deploy to AKS

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image with Git SHA tag
        run: docker build -t shubham6444/deployment-gamut:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push shubham6444/deployment-gamut:${{ env.IMAGE_TAG }}

      - name: Replace image tag in deployment.yaml
        run: |
          sed -i "s|image: shubham6444/deployment-gamut:.*|image: shubham6444/deployment-gamut:${{ env.IMAGE_TAG }}|g" deployment.yaml

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group my-aks-rg --name my-aks-cluster --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
